### ISSUE TITLE
Unable to login to server after installing the plugin

### ISSUE THREAD

**Issue by InvisibleOneL** [casperge/RealisticSeasons-issues#11]
### **Get the message "Exception Connecting:Quiet Exception : Unexpected packet received during login process! 0e0100" when trying to login.**

**_In the console I get -_**
23.10 17:52:15 [Server] WARN Exception in thread "pool-13-thread-1" java.lang.RuntimeException: java.util.NoSuchElementException: packet_handler
23.10 17:52:15 [Server] WARN at PacketListenerAPI_v3.9.8-SNAPSHOT.jar//org.inventivetalent.packetlistener.channel.INCChannel.lambda$addChannel$0(INCChannel.java:31)
23.10 17:52:15 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
23.10 17:52:15 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
23.10 17:52:15 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
23.10 17:52:15 [Server] WARN Caused by: java.util.NoSuchElementException: packet_handler
23.10 17:52:15 [Server] WARN at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
23.10 17:52:15 [Server] WARN at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
23.10 17:52:15 [Server] WARN at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
23.10 17:52:15 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61)
23.10 17:52:15 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:313)
23.10 17:52:15 [Server] WARN at PacketListenerAPI_v3.9.8-SNAPSHOT.jar//org.inventivetalent.packetlistener.channel.INCChannel.lambda$addChannel$0(INCChannel.java:29)
23.10 17:52:15 [Server] WARN ... 3 more

_The issue doesn't occur when RealisticSeasons isn't installed._

PaperMC 1.17.1 #349

Plugins installed (126): AdvancedEnchantments, AdvancedPortals, AdvancedRegionMarket, AdvancedSets, ArtMap, AuctionHouse, BannerMaker, BedRegen, BetterBowTrails*, BetterConcrete, BetterRTP, BuildBattle, BuycraftX, ChatColor2, ChatManager, ChatReaction, ChestShop, ChestSort, Chunky, Citizens, CleanroomGenerator, ClearLag, ClueScrolls, CMILib, ColoredSigns, CommandNPC*, CoreProtect, CrateReloaded, CrateReloadedNPC*, DailyRewardsPlus, DeathMessages, DeluxeMenus, DeluxeTags*, Denizen, DiscordSRV, dynmap, EditableSign, eGlow, EntityTrackerFixer, EpicRename, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExecutableItems, FarmControl, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), GadgetsMenu, GlobalBans, GlowAPI, Graves, GriefPrevention, GriefPreventionFlags, GSit, GUIShopSpawners, Harbor, HeadDatabase, HoloExtension, HolographicDisplays, HolographicExtension, IllegalStack, ImageMaps, Images, InvisibleItemFrames, Jobs, LagAssist, LeaderHeadsRevamped, LibsDisguises, LiteBans, Lottery, LuckPerms, LumberJack, MarriageMaster, mcMMO, MineableSpawners, Minepacks, MobArena, MorphRedeem, Multiverse-Core, MurderMystery, MyCommand, OldCombatMechanics, PacketListenerApi, PinataParty, PlaceholderAPI, Plan, PlayerParticles, PlayerVaults, PlayerWarps, PowerlessLamps*, ProtocolLib, ProtocolSupport, PvPManager, PyroFishingPro, PyroWelcomes, Rankup, RealisticSeasons, ResourceWorld, SafariNet, SCore, Scoreboard-revision*, ServerRestorer, SheepQuest, Spartan, SuperVanish, TAB, TempFly, Terra, TerraformGenerator, TicketManager, TimeIsMoney, TitleManager, TradeMe, TroddenPath, UltimateAutoRestart, UltimateStatistics, Vault, VentureChat, ViaVersion, VillageDefense, VoteParty, Votifier, VotingPlugin, WorldGuard

**Comment by casperge** [comment]
I think PacketListenerAPI is having issues working with protocollib. Do you know which of your plugins uses packetlistenerapi?

**Comment by InvisibleOneL** [comment]
I think it's the eGlow plugin and or the GlowAPI. using packetlistenerapi. So removed both as well as packetlistenerapi. Thought I may have fixed it, but just tried to login and am getting the same error, this time though it's not showing in console.

**I do have this warning showing in console but i'm unsure as to whether the seasons plugin is causing that, I'm pretty dumbfounded as to what plugin in causing an issue as the console makes no mention of anything specific.**

24.10 09:27:35 [Server] WARN Exception in thread "DefaultDispatcher-worker-2" java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.DelayKt.delay-VtjQ1oo(long, kotlin.coroutines.Continuation)'
24.10 09:27:35 [Server] WARN at dev.kord.common.ratelimit.BucketRateLimiter.delayUntilNextInterval(BucketRateLimiter.kt:44)
24.10 09:27:35 [Server] WARN at dev.kord.common.ratelimit.BucketRateLimiter.consume(BucketRateLimiter.kt:51)
24.10 09:27:35 [Server] WARN at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$4.invokeSuspend(Handler.kt:45)
24.10 09:27:35 [Server] WARN at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$4.invoke(Handler.kt)
24.10 09:27:35 [Server] WARN at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$4.invoke(Handler.kt)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:134)
24.10 09:27:35 [Server] WARN at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$3$2.emit(Collect.kt:137)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:341)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
24.10 09:27:35 [Server] WARN at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
24.10 09:27:35 [Server] WARN at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by InvisibleOneL** [comment]
Think I figured it out. Used a test server to put plugins in one by one and it's ProtocolSupport that causes the issue. Now able to login.

**Comment by casperge** [comment]
Awesome, that makes perfect sense. ProtocolSupport probably doesn't support custom biomes yet, required for the season colours. This was added in mc version 1.16, so everything below glitches out. Maybe try viabackwards and see what it does.

**Comment by InvisibleOneL** [comment]
Will do thanks so much for the help, loving the plugin now

**Comment by casperge** [comment]
No problem, glad we got it sorted. Have fun!
