### ISSUE TITLE
Compatible with Iris World Gen - Custom Biome Colors?

### ISSUE THREAD

**Issue by SGirl-Zockt** [casperge/RealisticSeasons-issues#114]
Hey,

Is your Plugin Compatible whit Iris World Gen - Custom Biome Colors?
https://www.spigotmc.org/resources/iris-world-gen-custom-biome-colors.84586/

mfg
SGirl

**Comment by casperge** [comment]
Yes, but you'll need to tell the plugin what to do with the custom biomes. If you're running a professional server I highly suggest doing this separately for every iris biome. You could also create one configuration file for all iris biomes but that could feel a bit off. Follow notes in /biomes/CUSTOM_EXAMPLE.yml for more details
