### ISSUE TITLE
Time set offest broken

### ISSUE THREAD

**Issue by kevinschenkenbe** [casperge/RealisticSeasons-issues#118]
time-sync-offset is set to -5000 but time in server is stuck to gmt when trying to set time to est

**Comment by casperge** [comment]
Sorry for completely looking over your issue, if you haven't figured it out yet: try sticking with time-sync-timezone. More info here: [time-sync-timezone](https://wiki.realisticseasons.com/configuration/calendar-and-custom-events#synchronizing-with-real-time)
