### ISSUE TITLE
 Light Recouses from Light souses #suggestion

### ISSUE THREAD

**Issue by editon96** [casperge/RealisticSeasons-issues#133]
Hey I see the new Update from you great Plugin and think about thome things...
If the Torch an Lava can heat you up would it be awsoume to have the Items Torch in the hand 
and then It heat you up too and gives light around the player.

I think that would be cool!

**Comment by casperge** [comment]
Hello, you could easily do that with the custom item system explained here: [https://wiki.realisticseasons.com/temperature/custom-items](https://wiki.realisticseasons.com/temperature/custom-items). Hope this helps
