### ISSUE TITLE
Wrong week day when executing /rs getinfo

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#135]
Hi folks,

I've installed the current nulled version (7.44) of RealisticSeasons on my PaperMC server. The plugin does work very well and fine, but when I'm executing the command /rs getinfo, the following information "Current day: Wednesday, April 14, Year 2022" will be shown in the chat. But today isn't a Wednesday, today is a Thursday because the 1st January of this year was a Saturday. Is this a very annoying shitty bug and if yes, can this get be fixed asap please? Sorry for swearing and sorry for owning a nulled version of this plugin, my parents don't allow me to pay for Spigot plugins, so I had to decide to choose a nulled version from https://blackspigot.com.

Sincerely yours,
Atten007😊

**Comment by casperge** [comment]
Hello Atten007,

Honestly blown away by the fact that you are asking for support and the entitlement. I understand that your parents do not allow you to buy plugins, but that is absolutely no reason to steal and on top of that expecting the author to help you. If you steal a bike and it breaks, do you also expect the original owner to repair it for you?
