### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by Dabaski** [casperge/RealisticSeasons-issues#139]
I have an idea that would be good, when a player logs on it stores a basic geolocation data to tell where the player is from. Use that to convert the temperature information for those who live in different areas that use different means of measuring temperature. 

AKA

If you live in the USA, Auto detect and set it as Fahrenheit (F)
If you live in Europe, Auto detect and set it as Celsius (C)

**Comment by Dabaski** [comment]
Also tell Coffee2go I said hi

**Comment by casperge** [comment]
I added the command /togglefahrenheit in v9.0.8, geolocation not yet. May come later.

**Comment by casperge** [comment]
GeoLocation added
