### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#146]
[Removed]

**Comment by casperge** [comment]
Hi Atten007,

Very suprised you're back after what I said to you. I do not appreciate people stealing my work, please do not post again in this github. Plugins take hunderds of hours to make and those working hours are worth the same as any job. I understand that you're young and you may not understand leaking stuff is very serious. It takes a hell lot of nerves to contact a developer for help with a leak combined with you thinking I owe you something. Please remove all files related to RealisticSeasons from your website or legal action will be taken.

**Comment by Atten007** [comment]
Already removed

**Comment by Atten007** [comment]
> Hi Atten007,
> 
> Very suprised you're back after what I said to you. I do not appreciate people stealing my work, please do not post again in this github. Plugins take hunderds of hours to make and those working hours are worth the same as any job. I understand that you're young and you may not understand leaking stuff is very serious. It takes a hell lot of nerves to contact a developer for help with a leak combined with you thinking I owe you something. Please remove all files related to RealisticSeasons from your website or legal action will be taken.

I've uploaded it on my website and it WON'T be removed from it!

**Comment by casperge** [comment]
As you wish, I'll contact you. Remember that leak websites have a legal construction that makes it hard for me to DMCA, but you have not.
