### ISSUE TITLE
Placeholder do not display well

### ISSUE THREAD

**Issue by YKDZ** [casperge/RealisticSeasons-issues#163]
%rs_bottle_icon%
%rs_temperaturecolor%
When parsed these two placeholder with PlaceholderAPI like "/papi parsed me %rs_temperaturecolor%", nothing will be displayed.

**Comment by casperge** [comment]
Hello, both these placeholders are supposed to be empty (most of the time). For example, %rs_temperaturecolor% is only a color code (invisible unless you add characters after it, like the player's temperature) and %rs_bottle_icon% will display a bottle icon if the player has the water-drinking cooling down effect.
