### ISSUE TITLE
Faraway chunks

### ISSUE THREAD

**Issue by PaladinFallen** [casperge/RealisticSeasons-issues#171]
https://pastebin.com/ZYRNXeGz

Still getting this issue with 10.0.2

**Comment by PaladinFallen** [comment]
Still getting the error with 10.0.5, I'm going to disable it in the world, restart the server, then re-enable it and see if the error still comes about.

**Comment by casperge** [comment]
Are there any players near the world border?

**Comment by PaladinFallen** [comment]
No none at all, but before I do anything I'm going to see what is there because it's actually outside of the loaded area and no one has been there..

**Comment by PaladinFallen** [comment]
Okay update, literally tp there and nothing there out of the norm. I cleared the literal five blocks from bedrock to game height from air to cobble stone thinking it would clear something. Disabled seasons, restarted server, the enabled it again. Still having the same issue. I'm also using Terralith could it be a chunk/biome thing?

**Comment by casperge** [comment]
Thank you, this confirms to me that RS is not loading chunks close to players, but just completely random chunks

**Comment by PaladinFallen** [comment]
OKay, good news as of 10.0.06 the randomness of getting a faraway chunk has stopped; however, it still does it only once when the server has been restarted. That is the only time that I've seen it now.

**Comment by PaladinFallen** [comment]
[17:39:07] [Server thread/INFO]: [dynmap] Update render pause set to false
[17:40:25] [Server thread/WARN]: [RealisticSeasons] Plugin is getting a faraway chunk at (1875001, 447), this might cause issues.
[17:40:25] [Server thread/WARN]: [RealisticSeasons] Plugin is getting a faraway chunk at (1875001, 447), this might cause issues.
[17:40:25] [Server thread/WARN]: [RealisticSeasons] Plugin is getting a faraway chunk at (1875001, 447), this might cause issues.

So this happened and it created a 9MB log file for me. Same chunks, same everything.. Dynmap issue maybe?

**Comment by casperge** [comment]
I will test with dynmap, implementing some things tomorrow 👍

**Comment by casperge** [comment]
Can you try v10.0.9? It includes a debug mode specifically for chunk loading, you can enable it with /rs debug. Some errors should start appearing after a while

**Comment by PaladinFallen** [comment]
As soon as I get off work, I'll install it and run the debug for you.

**Comment by PaladinFallen** [comment]
Okay, so I updated paper to the latest version, 138, they have been doing things with chunks as well.

- 138: Re-add legacy getChunkAtAsynchronously to ChunkProviderServer 
- 137: Fix World#refreshChunk not working for chunks in no-tick range 

HOWEVER, good news there is no more random trying to get chunk info from over a million blocks away. So as of two server normal restarts and three people watching the log report. I can say this can be closed.

**Comment by ezriharmusial** [comment]
Found the Same problem, struggling on and off with it for almost 2 months now. Updating has removed the Flood of notifications, but not the Root-Cause of the problem:

Upon playerjoin in an empty server at worldspawn 0, Faraway chunks are generated automatically just beyond the 3 million block world border. (Re-)Creating at least region and POI files, even after removing them manually.

See the files here
![Screenshot 2023-10-23 232522](https://github.com/casperge/RealisticSeasons-issues/assets/901880/d5772445-c9c7-47c9-9971-07ccfbbee61c)

**Comment by ezriharmusial** [comment]
So i opened up the files in NBT Explorer to have a Look. And with my little understanding of Minecraft innerworkings I found that in the Region files, something is iteratively creating Chunk Structures, comprised of Section filled with nothing but air.

![Screenshot 2023-10-25 180423](https://github.com/casperge/RealisticSeasons-issues/assets/901880/acee6881-b3e8-45b2-b313-0dab934c7786)

**Comment by ezriharmusial** [comment]
For the POI files, something is creating 2 Chunk section records in the same chunks with nothing but 2 minecraft:home entries.

![Screenshot 2023-10-25 180448](https://github.com/casperge/RealisticSeasons-issues/assets/901880/2d98b5ed-a200-4cee-9dfe-6ab2c98adc73)

**Comment by ezriharmusial** [comment]
As a web developer, i'm used to looking into the Code. But as I am fairly new to minecraft. I don't know where to start to Debug this. 

Do any of you guys have some tips?

At least I have found that someone has the Same symptoms as I: realisticseasons flooding the console.
