### ISSUE TITLE
Synchronization of days only

### ISSUE THREAD

**Issue by KOTOKOPOLb** [casperge/RealisticSeasons-issues#175]
I read the instructions for synchronizing days without synchronizing the time, but did not understand how to do it right. I tried several combinations, but either nothing was synchronized or everything was synchronized (time and days).
I would like to sync only the days, i.e. so that the game days keep going and the days of the months are synchronized with real days.

**Comment by casperge** [comment]
Setting modify-daynight-length to false in the config.yml and sync-time-with-real-world to true in the calendar.yml should do the trick. Let me know if it doesn't work

**Comment by KOTOKOPOLb** [comment]
If you do as you said, the days are synchronized, but the time is also
![image](https://user-images.githubusercontent.com/82699565/188934031-0dbcf0b7-e06a-427f-a4b6-eed52440597f.png)

**Comment by casperge** [comment]
You have to manually run /gamerule doDayLightCycle true once, can you try that?

**Comment by KOTOKOPOLb** [comment]
I used this command but the problem didn't go away

**Comment by casperge** [comment]
Is it only the time in /season that isn't syncing or also the actual time of day?

**Comment by KOTOKOPOLb** [comment]
I'm sorry, I didn't notice. By entering the command, the problem was solved. Thank you!

**Comment by KOTOKOPOLb** [comment]
After restarting the server, the problem returned, the value of "gamerule doDaylightCycle" was again set to False

**Comment by casperge** [comment]
What RealisticSeasons versions are you using?

**Comment by KOTOKOPOLb** [comment]
9.1.3

**Comment by casperge** [comment]
Updating should fix it, you will also get subseasons and a lot of performance improvents :)

**Comment by KOTOKOPOLb** [comment]
Unfortunately I don't have the official version of the plugin and 9.1.3 is the newest version. It turns out that if I find / buy a new version of the plugin, then the problem should go away?

**Comment by casperge** [comment]
If you buy the plugin, you will always get the latest version. This github is for buyers only however, so I will close this issue. I have no association with the websites that offer it for free and I did not grant them the permission to distribute anything. You need to contact them for help :)

**Comment by KOTOKOPOLb** [comment]
But anyway thanks for the help
