### ISSUE TITLE
Remove Protocollib

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#178]
It may be nice when the dependency Protcollib can be removed from RealisticSeasons in a future update because I don't want to install it on my server due to the lack of 1.19.2 support.

It may be also nice, when support for MCPE and Mohist servers can be added. More information here: https://github.com/casperge/RealisticSeasons-issues/issues/177.

Sincerely yours,
Atten

**Comment by casperge** [comment]
Hello, that would remove the colors, so ProtocolLib will always be needed
