### ISSUE TITLE
Does it work on Cardboard?

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#189]
Hello,

Recently, I bought the plugin and now I'm planning to open a new server for a very big project. I want to use Bukkit Plugins together with Fabric mods, Cardboard can do this, but I'm not sure whether the plugin supports cardboard or not. Does it support the Cardboard mod? Or should I use the Fabric Seasons mod for this if Cardboard doesn't work?

Greetings,
Atten 😊

**Comment by casperge** [comment]
Hello, I have not tested cardboard but so far any type of modded server has not worked
