### ISSUE TITLE
Support for the Southern hemisphere?

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#190]
Hello,

I have my own Minecraft server and I want to have one world with the southern hemisphere seasons and one with the northern hemisphere seasons there. On the southern hemisphere, there are reversed seasons (e.g. June Northern hemisphere = Summer, Southern hemisphere = Winter). Is it possible to add support for the southern hemisphere seasons in a future update? And is it possible to have one world with normal seasons for the northern hemisphere and one world with reversed seasons for the southern hemisphere?

Greetings,
Atten😊

**Comment by casperge** [comment]
Interesting idea
