### ISSUE TITLE
Configuration file for animals?

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#191]
Hello,

I have this plugin on my server and currently, it's winter on my world. In the winter, there are spawning many animals that fit the winter season, but I want, that some of these animals shouldn't spawn because it's a bit annoying, so the idea, that a configuration file, that controls, which and how many animals should be spawned and which not. This may be a nice feature that can be added in v.11.0. The file can look like this:

ANIMALS.yml
spring:
animal-1: true
animal-2: false
amount-1: 2
amount-2: 4

summer:
animal-1: true
animal-2: false
amount-1: 2
amount-2: 4

autumn/fall:
animal-1: true
animal-2: false
amount-1: 2
amount-2: 4

winter:
animal-1: true
animal-2: false
amount-1: 2
amount-2: 4

animal-1 and animal-2 can here be replaced with the Minecraft animal names.

Greetings,
Atten 😊

**Comment by casperge** [comment]
Hello Atten, great idea! Something like this could be added to the configuration update
