### ISSUE TITLE
change type of %rs_temperature% placeholder from string to int, or create two placeholder %rs_temperature_int(or string)%

### ISSUE THREAD

**Issue by newcovid** [casperge/RealisticSeasons-issues#192]
I think this change is good, and I need it.please

**Comment by casperge** [comment]
I can't find anything about int placeholders, can you link a plugin that has it?

**Comment by newcovid** [comment]
Yes, I try to use the executableitems plugin to write some items that extend the temperature system. I hope to use the int placeholders to do some conditional restrictions.

**Comment by newcovid** [comment]
It requires a variable containing only numbers, not followed by a ° C

**Comment by newcovid** [comment]
I'm so sorry that my statement is not accurate enough.Because my mother tongue is not English.
What I mean is that I need a placeholder that contains only numbers, not the following temperature unit symbols like Celsius and Fahrenheit.

**Comment by casperge** [comment]
Forgot about that, will be included next update

**Comment by casperge** [comment]
Added
