### ISSUE TITLE
Support for Cherry blossom grove when 1.19.4 gets released

### ISSUE THREAD

**Issue by Atten007** [casperge/RealisticSeasons-issues#193]
Hello casperge,

I hope, you're fine! Your plugin is very cool, but I want, that you add one new feature when 1.19.4 is released:

- Support for the cherry blossom grove biome.

I'll be very happy when you can ad support for this new biome soon!

Greetings,
Atten 😊

**Comment by casperge** [comment]
Sure, I will think of some ways to integrate it
