### ISSUE TITLE
Upon restart when doing commands they will just respond with the command instead of something

### ISSUE THREAD

**Issue by aramshiva** [casperge/RealisticSeasons-issues#195]
Example: /season says /season instead of telling you about the season **ON THE FIRST RESTART** only. Fixed when you delete the RealisticSeasons Folder.

**Comment by aramshiva** [comment]
Functions of RealisticSeasons still work like the all night in winter but the commands dont

**Comment by casperge** [comment]
Hello, there is probably an error somewhere in your console. Can you find any?

**Comment by aramshiva** [comment]
This is what shows in console when I send the command:
<img width="368" alt="Screenshot 2023-03-05 at 7 52 22 AM" src="https://user-images.githubusercontent.com/79479940/222971094-db95c3cf-355c-45d8-a0f6-5ba245e6311c.png">

**Comment by casperge** [comment]
Strange, is there anything at startup?

**Comment by aramshiva** [comment]
<img width="630" alt="Screenshot 2023-03-05 at 7 55 43 AM" src="https://user-images.githubusercontent.com/79479940/222971254-f83b05e7-2b59-4a07-ac32-7bc4413751a2.png">
<img width="638" alt="Screenshot 2023-03-05 at 7 55 59 AM" src="https://user-images.githubusercontent.com/79479940/222971267-f67c305b-3ba2-4f52-a52f-a2bcad2651f9.png">
<img width="625" alt="Screenshot 2023-03-05 at 7 56 14 AM" src="https://user-images.githubusercontent.com/79479940/222971275-9806fd58-52a5-4145-8a5c-2d665d6be572.png">
<img width="625" alt="Screenshot 2023-03-05 at 7 56 42 AM" src="https://user-images.githubusercontent.com/79479940/222971300-bf8a3966-961c-4295-812d-e74d1fb08b65.png"
6f-8ae565f70e2c.png">
<img width="633" alt="Screenshot 2023-03-05 at 7 56 59 AM" src="https://user-images.githubusercontent.com/79479940/222971314-8f43f2a6-a50b-4ed1-82aa-bb1a8cf68f9b.png">
>

**Comment by aramshiva** [comment]
never mind looks like it freaks out whenever your event configuration is wrong and the entire plugin breaks. fixed the custom event file and its fixed!
