### ISSUE TITLE
Attempting to join the server is resulted in "Disconnected"

### ISSUE THREAD

**Issue by ZeroTwoO2** [casperge/RealisticSeasons-issues#197]
After installing protocol lib 5.0.0 SNAPSHOT and then RealisticSeasons, trying to join the server is impossible. I can't join due to the server saying "Disconnected" and nothing else. No error on startup no nothing

**Comment by casperge** [comment]
Hello, what server type and version are you playing on? Also, they may be some other clues in the logs which you may easily miss. Can you upload a full log?

**Comment by ZeroTwoO2** [comment]
Server version is 1.18.2, and these and i'm playing on 1.19.2 with viaversion installed on the server. 
[latest.log](https://github.com/casperge/RealisticSeasons-issues/files/11241699/latest.log)

**Comment by ZeroTwoO2** [comment]
an update? it's been 4 days and if it doesn't work i would like a refund

**Comment by casperge** [comment]
I will give you a refund, what is your spigot username?

**Comment by ZeroTwoO2** [comment]
[Zero_RTR](https://www.spigotmc.org/members/zero_rtr.907231/)

**Comment by ZeroTwoO2** [comment]
LMK when you have sent me my money back

**Comment by casperge** [comment]
Money is on its way
