### ISSUE TITLE
Plugin sets entire minecraft folder owner to UNKNOWN

### ISSUE THREAD

**Issue by ArmonicPvP** [casperge/RealisticSeasons-issues#229]
When running my Minecraft server in Linux, upon startup RealisticSeasons sets the owner to UNKNOWN and I am no longer able to edit the files. If I change it back to nobody, which is the default, RealisticSeasons gives an "Access denied" error. The plugin should not be modifying ownership of my entire Minecraft folder.

**Comment by ArmonicPvP** [comment]
Edit: When this happens, I can no longer start the server back up because I get a permission denied error. I have to change the folder permission back to "nobody" recursively to fix the issue.

**Comment by casperge** [comment]
That's really bad, are you also running other plugins on your server? Did that work fine before?

Also, what server software are you running? (Paper, spigot etc)

**Comment by ArmonicPvP** [comment]
Worked fine until I installed RealisticSeasons. Removing it fixed the issue. I had to rollback afterwards because all the plugins which loaded after couldnt access their files. I'm on the latest Paper build of 1.20.4. Also running minecraft in docker with Java 17 I believe

**Comment by casperge** [comment]
Okay, does it happen right away on startup? Or only after shutdown/restart of the server?

**Comment by ArmonicPvP** [comment]
i am an idiot. as it turns out, i had a random startup script that was detecting wrong permissions and then setting them to 1000 instead of 100. great plugin, sorry for wasting your time
