### ISSUE TITLE
Issue installing  plugin

### ISSUE THREAD

**Issue by yoyoy123** [casperge/RealisticSeasons-issues#33]
When i install the plugin on my server this happends if i type /rs or any other command 
and there happends nothing do you now how to fix this

**Comment by yoyoy123** [comment]
file:///C:/Users/artur/OneDrive/Afbeeldingen/rs.jpg

**Comment by Loapu** [comment]
You know the link you posted is for your file system on your personal computer? Please upload the screenshot directly here on GitHub. Also did you follow the installation directions outlined on the plugins Spigot page?

**Comment by casperge** [comment]
I think this one is fixed, a broken version was uploaded yesterday and released a fix. Could you confirm that it is working again yoyoy123?
