### ISSUE TITLE
Passive Strays

### ISSUE THREAD

**Issue by PaladinFallen** [casperge/RealisticSeasons-issues#42]
Having issues with strays, using the custom-events command, after the event has passed they are now passive. This is true for every stray spawned in as well.

**Comment by casperge** [comment]
Hey PaladinFallen, what custom event command are you talking about? If you're talking about a custom event in custom-events.yml, could you send me the event?

**Comment by PaladinFallen** [comment]
Christmas-event:
         enabled: true
         name: "&6Christmas Eve and Christmas Day"
         display-event: true
         times:
            event-start:
               date: 12/24
            event-stop:
               date: 12/26
         commands:
            start:
               - "&aRelax knowing these days will pass and no mob will bother you, and death will not be a loss for your items.."
               - "/difficulty peaceful"
               - "/gamerule keepInventory true"
            stop:
               - "/difficulty normal"
               - "/gamerule keepInventory false"

**Comment by casperge** [comment]
I think that is a Minecraft issue, don't think I can fix that. Strays survive the day as one of the only mobs, so I think that's why you only see passive strays. The rest of the mobs were just dead.
