### ISSUE TITLE
Suggestion: ability add/change the /season command (alias)

### ISSUE THREAD

**Issue by knniDE** [casperge/RealisticSeasons-issues#43]
hey, i would like to be able to change the /season command.
i have a german community server and would like to change the command for players.

**Comment by casperge** [comment]
Spigot/Bukkit doesn't allow developers to change their commands after compiling (they are in a separate yml file inside the jar). You can however register an alias yourself through bukkit. Open the commands.yml file located in the main server folder (the same folder as the spigot/server jar) and change the aliases section to this:

```
aliases:
  yournewcommandnamehere:
  - season
```
