### ISSUE TITLE
Sleeping doesn't appear to work correctly

### ISSUE THREAD

**Issue by untuned** [casperge/RealisticSeasons-issues#44]
When a player sleeps in a bed, it does not seem to skip to day. I'm not entirely sure it's this plugin, but nothing else I have messes with the day cycle.

**Comment by casperge** [comment]
Interesting, is sync-time-with-real-world in the calendar.yml on or off?

**Comment by untuned** [comment]
> Interesting, is sync-time-with-real-world in the calendar.yml on or off?

It is set to off. I've also noticed that turning temperature off, then back on again, seems to break the system? It's been set to true but hasn't actually activated in game for some reason.

**Comment by casperge** [comment]
Think it is a compatibility issue, the best idea would be to disable modify-daynight-length in the config.yml and turn on doDayLightCycle gamerule again in-game.
