### ISSUE TITLE
RealisticSeasons does not seem to work with the doDaylightCycle gamerule

### ISSUE THREAD

**Issue by HenrikoMagnifico** [casperge/RealisticSeasons-issues#45]
It seems that the gamerule "doDaylightCycle", which affects the day and night cycle, isn't respected by RealisticSeasons, which forces the time to progress even though the game rule has been set to false in any given world.

**Comment by casperge** [comment]
This is required for the custom day and night length. The plugin basically overrides the time system Minecraft has and that requires Minecraft's time system to be off. If you want to stop the daylight cycle in any world you should disable seasons there. You could also turn off the custom day/night length completely in the config.yml by turning off modify-daynight-length. This will make doDayLightCycle work again in all worlds.
