### ISSUE TITLE
Sudden Temp Change

### ISSUE THREAD

**Issue by MaxRingnalda** [casperge/RealisticSeasons-issues#54]
Hey there, I really love the Realistic Seasons Plugin! Now... I just noticed that sometimes at night that when I walk next to a torch I suddenly got damage. I tested this out and when there are sudden temperature changes I take damage... Is this even a thing? and if it is, is there a way to disable it?

https://user-images.githubusercontent.com/36833763/143404839-56591c6d-2760-4b36-893d-d9850fb660df.mp4

**Comment by casperge** [comment]
Hey MaxRingnalda, thank you for including a video, helps a lot. It is actually supposed to do the opposite: adding 2 hearts to the player's HP as a reward for having a good temperature. Some plugins don't like this however for some reason and deal you damage instead. You can change this effect to something else by changing HEALTH_BOOST in the temperature.yml boosts section to any potion effect. List of effects can be found here: 
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html

**Comment by MaxRingnalda** [comment]
Thanks and sorry for the late reply! So if the case that is ant to disable it completely, I would just have to remove that line
