### ISSUE TITLE
Custom month name translations

### ISSUE THREAD

**Issue by JinOuYongGu** [casperge/RealisticSeasons-issues#55]
I have noticed that there were week-days translations in file calendar.yml .
Like:
```
week-days:
  - Monday
  - ....
  - ....
```

I wish the month could have such translations too.

**Comment by casperge** [comment]
You can change the month names in the calendar.yml to whatever you like (in the list with their lengths etc), the plugin will recognize them. The month names and even the amount of months aren't hard coded.
