### ISSUE TITLE
[Feature Request] Integration with Bluemap

### ISSUE THREAD

**Issue by HenrikoMagnifico** [casperge/RealisticSeasons-issues#70]
Bluemap is an awesome plugin used to display server worlds on the web in full 3D. Sadly, it doesn't display biome colours from RealisticSeasons at all, which results in the world looking like summer all the time in Bluemap, even though there's snow everywhere. Integrated with Bluemap with RealisticSeasons would be a fantastic addition!

**Comment by casperge** [comment]
Biome colours can't be supported on map plugins sadly. RealisticSeasons only changes biomes through packets (this means that biome data is changed for the players right before it is sent to them). Map plugins like Bluemap read the biomes directly from the world, the only way to make those biomes RealisticSeasons is by actually changing the biomes in the world. A big point of my plugin however is that it doesn't change those. Hope this answers your question :)
