### ISSUE TITLE
Birch leaves

### ISSUE THREAD

**Issue by MishkoFreid** [casperge/RealisticSeasons-issues#71]
1.18.1. For some reason, birch leaves do not change their color when the season changes. Ths is BIRCH_FOREST.yml file and screenshot from the game.
![Безымянный](https://user-images.githubusercontent.com/96202762/146247563-905f4c8a-79b9-44f7-9f6e-ca2d6f108a06.png)
![2021-12-15_20 49 16](https://user-images.githubusercontent.com/96202762/146247622-8204ca71-ed07-4576-a174-c8b122c81549.png)

**Comment by casperge** [comment]
Minecraft issue, birch leaves have a hard coded color. No way for me to change them, results in occasional ugly forests.
