### ISSUE TITLE
Why doesn't appear temperature.yml of file 

### ISSUE THREAD

**Issue by coolshing** [casperge/RealisticSeasons-issues#73]
I use purpur 1.16.5 to start server,but don't appear temperature.yml.Why doesn't temperature.yml of file appear
![Image 1](https://user-images.githubusercontent.com/79793171/146879358-ff7da102-30ce-4f72-b33d-4db105975207.png)

**Comment by casperge** [comment]
Hmmm, any errors?

**Comment by coolshing** [comment]
Oh!Here is it.
[latest.log](https://github.com/casperge/RealisticSeasons-issues/files/7763106/latest.log)

**Comment by casperge** [comment]
Thank you, I'll release an update fixing this later today.
