### ISSUE TITLE
Dynmap pausing doesnt seem to work correctly

### ISSUE THREAD

**Issue by Paradox101** [casperge/RealisticSeasons-issues#95]
Check https://map.meowcraft.online/, dynmap continues to render in winter it seems.

In config I got this:

dynmap-pause-renders-in-winter: true

![Untitled](https://user-images.githubusercontent.com/96799824/147840862-a0c50257-650b-40d5-8b2d-0bd7ee55a4e7.png)

**Comment by casperge** [comment]
Interesting, thank you for reporting. Will look into it

**Comment by casperge** [comment]
Fixed
