### ISSUE TITLE
The plugin should be convenient for users in other regions

### ISSUE THREAD

**Issue by xzrui** [casperge/RealisticSeasons-issues#96]
Hello, author!I hope you can provide boolean settings for events in the plugin such as whether it rains in the season.
Because your plugin is actually very popular, I am a Chinese user. However, the seasonal phenomenon in China is completely opposite to the seasonal phenomenon built in your plugin!
For example, in China, we often rain in summer instead of autumn.
I hope to be able to modify the boolean of these seasonal phenomena so that the plugin's matches the weather phenomena in my players' country.

**Comment by casperge** [comment]
Sure, sounds like a good idea
